(() => {
  const kind = document.body.dataset.dashboard;
  const noun = kind === 'board' ? 'Board' : 'Note';
  const title = kind === 'board' ? 'My handsome face' : 'Trip to Ogbomoso';
  const cards = [...document.querySelectorAll('.card-grid')];


  const card = (pinned, index) => `<article class="dashboard-card" data-pinned="${pinned}"><div class="card-preview ${kind}-preview">${kind === 'note' ? '<div class="palette"><span></span><span></span><span></span><span></span></div><span class="sticky red">The trip was memorable; see you around 4pm.</span><span class="sticky blue">The trip was memorable; see you around 4pm.</span><span class="sticky green">The trip was memorable; see you around 4pm.</span>' : ''}</div><button class="menu-toggle" type="button" aria-label="Open ${noun} menu">•••</button><div class="card-menu"><button class="close-menu" type="button" aria-label="Close menu">×</button><button type="button" data-action="pin">♙ ${pinned === 'true' ? 'Unpin' : 'Pin'}</button><button type="button" data-action="delete">♙ Delete</button></div><div class="card-meta"><div class="card-title">${index === 0 ? title : title}</div><div class="card-time">Edited 10 minutes ago</div></div></article>`;

  const render = () => { const items = JSON.parse(localStorage.getItem(`noteboards-${kind}s`) || 'null') || [{pinned:true},{pinned:true},{pinned:true},{pinned:true},{pinned:false},{pinned:false},{pinned:false},{pinned:false}]; cards[0].innerHTML = items.filter(x=>x.pinned).map((x,i)=>card('true',i)).join(''); cards[1].innerHTML = items.filter(x=>!x.pinned).map((x,i)=>card('false',i)).join(''); };

  const save = () => { const items=[...document.querySelectorAll('.dashboard-card')].map(x=>({pinned:x.dataset.pinned==='true'})); localStorage.setItem(`noteboards-${kind}s`,JSON.stringify(items)); };

  const toast = (message) => { const el=document.querySelector('.toast'); el.textContent=message; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),2500); };

  render();

  document.addEventListener('click',(event)=>{ const toggle=event.target.closest('.menu-toggle'); 
    const cardEl=event.target.closest('.dashboard-card'); if(toggle){document.querySelectorAll('.card-menu.open').forEach(x=>x.classList.remove('open'));toggle.nextElementSibling.classList.add('open');return;} if(event.target.closest('.close-menu')){event.target.closest('.card-menu').classList.remove('open');return;} const action=event.target.dataset.action;if(action&&cardEl){if(action==='delete'){cardEl.remove();toast(`${noun} deleted.`);}else{cardEl.dataset.pinned=String(cardEl.dataset.pinned!=='true');toast(`${noun} ${cardEl.dataset.pinned==='true'?'pinned':'unpinned'}.`);}save();render();}else if(!event.target.closest('.card-menu'))document.querySelectorAll('.card-menu.open').forEach(x=>x.classList.remove('open'));});
  const openCreateModal=()=>{const modal=document.createElement('div');modal.className='modal-backdrop';modal.innerHTML=`<section class="create-modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div class="modal-top"><div><h2 class="modal-title" id="modal-title">Create ${noun}</h2><p class="modal-copy">Give your new ${noun.toLowerCase()} a name to get started.</p></div><button class="modal-close" type="button" aria-label="Close">×</button></div><form novalidate><label class="modal-label" for="new-item-name">${noun} name</label><input class="modal-input" id="new-item-name" type="text" maxlength="60" placeholder="Name your ${noun.toLowerCase()}" aria-describedby="new-item-error" /><p class="modal-error" id="new-item-error" aria-live="polite"></p><div class="modal-actions"><button class="modal-cancel" type="button">Cancel</button><button class="modal-submit" type="submit">Create ${noun}</button></div></form></section>`;const close=()=>modal.remove();document.body.append(modal);const input=modal.querySelector('input');input.focus();modal.querySelector('.modal-close').onclick=close;modal.querySelector('.modal-cancel').onclick=close;modal.onclick=(event)=>{if(event.target===modal)close()};modal.onkeydown=(event)=>{if(event.key==='Escape')close()};modal.querySelector('form').onsubmit=(event)=>{event.preventDefault();const name=input.value.trim();const error=modal.querySelector('.modal-error');if(name.length<2){error.textContent=`Enter at least 2 characters for the ${noun.toLowerCase()} name.`;input.focus();return;}const saved=JSON.parse(localStorage.getItem(`noteboards-${kind}s`)||'[]');saved.push({pinned:false,name});localStorage.setItem(`noteboards-${kind}s`,JSON.stringify(saved));close();render();toast(`${noun} created.`)}};
  document.querySelector('.create-button').addEventListener('click',openCreateModal);
})();
